### PR TITLE
Sort fixes

### PR DESCRIPTION
**Pull request by supertunaman**
I made these changes for my own [personal blog](https://supertunaman.com/blog). Before, the posts seemed to be getting sorted by filename of the original files, which was not ideal.

I made [another change](https://git.sr.ht/~supertunaman/ephemeris/commit/f10305bb464b80a9816b5b13327ec8c1037a4d33) that allowed use of the subdirectory for my blog, but I'm not strong enough in golang to make it usable for everybody. I left that out of this PR.

### CODE REVIEW

**Comment by skx** [comment]
A quick glance makes me think your changes are reasonable, thank-you for contributing them :)

[My own blog](https://blog.steve.fi/) seems to show things correctly, but I realize now that might be an artifact of the way I store the input:

     data/
     data/2021
     data/2021/100.txt
     data/2021/101.txt
     data/2020/99.txt
     data/2020/98.txt

I'll test before I merge, but i don't expect any surprises.  Thanks again!

**Comment by skx** [comment]
On the topic of prefixes I see this blog-post:

* https://supertunaman.com/blog/gratitude__open_source_frontend.html

The tags there link to `/tags/xxx` which are broken.  I'm surprised setting `Prefix` to https://supertunaman.com/blog/ doesn't suffice for you - it might be that too many things are hardwired.

I'd be willing to work on that for/with you if you were to open a new issue/pull-request.  Off-hand I guess things like this:

```
    <link rel="alternate" type="application/rss+xml" href="{{.Prefix}}index.rss" title="RSS feed for {{.Prefix}}">
    {{template "data/inc/css.tmpl"}}
  </head>
  <body>
    <div class="header">
      <a href="{{.Prefix}}" class="logo">Steve Kemp's Blog<span> - Debian &amp; Free Software</span></a>
      <div class="header-right">
        <a href="/about/">About</a>
        <a href="/archive/">Archive</a>
```

Need to have `{{.Prefix}}` inserted infront of most of the links, e.g. `/tags`, `/about/`, etc.

**Comment by skx** [comment]
* Included your patch
* Rebuilt my blog
* Suddenly posts from 2005 were the most recent.

Something isn't entirely right.  I'll need to do some debugging..

**Comment by supertunaman** [comment]
Uh oh!

**Pull request closed without merging**
